// flow-typed signature: 82e55523c178a1d5d5b6cc723d144370
// flow-typed version: <<STUB>>/update_v^0.7.4/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'update'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'update' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'update/bin/update' {
  declare module.exports: any;
}

declare module 'update/lib/cli' {
  declare module.exports: any;
}

declare module 'update/lib/commands' {
  declare module.exports: any;
}

declare module 'update/lib/commands/add' {
  declare module.exports: any;
}

declare module 'update/lib/commands' {
  declare module.exports: any;
}

declare module 'update/lib/commands/remove' {
  declare module.exports: any;
}

declare module 'update/lib/commands/silent' {
  declare module.exports: any;
}

declare module 'update/lib/commands/version' {
  declare module.exports: any;
}

declare module 'update/lib/list' {
  declare module.exports: any;
}

declare module 'update/lib/updatefile' {
  declare module.exports: any;
}

declare module 'update/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'update/bin/update.js' {
  declare module.exports: $Exports<'update/bin/update'>;
}
declare module 'update/index' {
  declare module.exports: $Exports<'update'>;
}
declare module 'update/index.js' {
  declare module.exports: $Exports<'update'>;
}
declare module 'update/lib/cli.js' {
  declare module.exports: $Exports<'update/lib/cli'>;
}
declare module 'update/lib/commands.js' {
  declare module.exports: $Exports<'update/lib/commands'>;
}
declare module 'update/lib/commands/add.js' {
  declare module.exports: $Exports<'update/lib/commands/add'>;
}
declare module 'update/lib/commands/index' {
  declare module.exports: $Exports<'update/lib/commands'>;
}
declare module 'update/lib/commands/index.js' {
  declare module.exports: $Exports<'update/lib/commands'>;
}
declare module 'update/lib/commands/remove.js' {
  declare module.exports: $Exports<'update/lib/commands/remove'>;
}
declare module 'update/lib/commands/silent.js' {
  declare module.exports: $Exports<'update/lib/commands/silent'>;
}
declare module 'update/lib/commands/version.js' {
  declare module.exports: $Exports<'update/lib/commands/version'>;
}
declare module 'update/lib/list.js' {
  declare module.exports: $Exports<'update/lib/list'>;
}
declare module 'update/lib/updatefile.js' {
  declare module.exports: $Exports<'update/lib/updatefile'>;
}
declare module 'update/lib/utils.js' {
  declare module.exports: $Exports<'update/lib/utils'>;
}
